### ISSUE TITLE
Initial Nextcloud setup against mariadb fails for mariadb >= 10.6

### ISSUE THREAD

**Issue by Hurricos** [LaboratoryB/nextcloud-docker#2]
This [appears to be a known issue with Nextcloud server's defaults.](https://github.com/nextcloud/server/issues/25436).

See screenshot:

![image](https://user-images.githubusercontent.com/2000409/141828536-e26e5f37-c120-49b1-a10b-36ad855a6f6d.png)

This issue has been circling since the [MariadB 10.6.0 release](https://jira.mariadb.org/browse/MDEV-22367), which changes compressed page tables and makes them not writable by InnoDB, in preparation for deprecating this feature.

## Solutions

I was initially unsure whether locking MariaDB to 10.5, which [has been a solution deployed in practice for Nextcloud's official Docker](https://github.com/nextcloud/docker/pull/1537#issuecomment-882002301), is the best way to go, but it [appears that this is the official solution](https://github.com/nextcloud/server/issues/25436#issuecomment-883213001).

**Comment by aaronsilber** [comment]
@Hurricos Thanks for the report. I have no concerns about locking this to MariaDB 10.5. I expect a solution will come in the future that will enable us to take MariaDB 10.6 and newer, and when it does we can update this.
